# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 305749a2dc75af46022af5f377a185f8232bf6f21be704c21f376fdc5e7b7a182e5921fac78a5171bf0d2da597c495f8f34271139b6fbed54db89157c9ae418e

test:
  secret_key_base: 9c423d3b4d703b0bdcad63d911253346aefc9b45d5b2e4f15c954e12827da125888ba7a9c0a33f89f49334130b7c06a58acf5aefab3f3c3e193e232c4ece7ae8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
